[package]
name = "hqm-proxy-rust"
version = "1.0.0"
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["multipart", "json", "blocking"] }